# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ninrod does Rust
email: no@spam.com
description: > # this means to ignore newlines until "baseurl:"
  personal webpage of ninrod, a.k.a Filipe Silva. A blog about the Rust programming language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ninrod.github.io" # the base hostname & protocol for your site
twitter_username: filipetwits
github_username:  ninrod

# Build settings
markdown: kramdown
